### PR TITLE
Add 🦶🔫

### PR DESCRIPTION
**Pull request by LilithHafner**
I find that using Julia after calling this method has a lot more thrill and intensity. It's a tool for increased productivity—you have to work fast before something bad happens.

### CODE REVIEW

**Comment by theogf** [comment]
That looks absolutely atrocious, if you merge master, the CI should pass.

**Comment by LilithHafner** [comment]
> if you merge master, the CI should pass.

I'm assuming you're referring to "🖐️", which, by the way, is a much more reasonable default branch than "master"

**Comment by theogf** [comment]
Indeed, sorry things obviously go very fast in this package.

**Comment by theogf** [comment]
> I'm assuming you're referring to "🖐️", which, by the way, is a much more reasonable default branch than "master"

Now comes the complicated question of updating the registry with the new branch name.

**Comment by LilithHafner** [comment]
Shouldn't registries point to the default branch, whatever that happens to be?

**Comment by theogf** [comment]
> Shouldn't registries point to the default branch, whatever that happens to be?

Does not look like it: https://github.com/JuliaWTF/WatchJuliaBurn.jl/commit/c279063e011def2261626862461386179183bcf3

**Comment by LilithHafner** [comment]
Oh no.

**Pull request merged**
