### PR TITLE
🥩"raw strings"

### PR DESCRIPTION
**Pull request by mschauer**

### CODE REVIEW

**Comment by theogf** [comment]
Hahaha I love it! can you also add it to the README?

**Comment by mschauer** [comment]
Let's see if I can do it without touching git :-D

**Comment by theogf** [comment]
You can go on your fork select your branch and edit the README directly!

**Comment by mschauer** [comment]
I found a less practical way!

**Comment by theogf** [comment]
Nice to see you follow the philosophy of the package

**Pull request merged**
