### PR TITLE
Launch space invaders on space

### PR DESCRIPTION
**Pull request by LilithHafner**
When triage was discussing JuliaLang/julia#33875, we discussed the prevalence of keyboard soup scattered across the ecosystem where different packages use different "magic keys" to launch repl modes. @oscardssmith mentioned "you can even press space for space invaders"

While several closed-minded triagers assumed he was joking, the merits of this keybinding are quite apparent

- Space is a clear mnemonic for space invaders
- The space bar is conveniently located in the center of the widely used [BÉPO](https://en.wikipedia.org/wiki/B%C3%89PO) keyboard layout, and has a large surface area for user convince
- No self-respecting line of Julia code entered at the REPL begins with a space

This PR makes pressing space at an empty `julia>` prompt launch space invaders. 

In theory, this could be implemented as a package extension with REPL. However, according to several peer reviewed studies ([source](https://lilithhafner.com/dangers-of-decreased-compile-time)), there is growing concern among the Julia community that compile and load times are getting too low. This has resulted in decreased operational readiness in sword fighting atop rolling chairs (c.f. https://xkcd.com/303/). In an effort to rectify the situation, I didn't bother implementing this as a package extension.

As for the file name, while `".jl"` is a classic ending, I think we can all agree that `" .jl"` is a bad file name, so I picked something a little more plain.

### CODE REVIEW

**Review by oscardssmith — APPROVED** [review]
lgtm.

**Comment by theogf** [comment]
Tested and approved!

**Review by theogf — APPROVED** [review]

**Comment by adrhill** [comment]
This needs a release asap!

Can we document it in the README? Maybe we don't need to, since it's such an intuitive feature in the first place.

**Comment by theogf** [comment]
https://github.com/JuliaRegistries/General/pull/105025#issuecomment-2059539619

image

**Comment by ericphanson** [comment]
[it's not allowed on windows apparently](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names/31976060#31976060), so [we don't allow it](https://github.com/JuliaRegistries/RegistryCI.jl/blob/0cd9521b075913dc5b92485ca264b23daa6db9fb/src/AutoMerge/guidelines.jl#L631-L652)

**Comment by kellertuer** [comment]
Oh, that is sad, then even ` .jl` would not help for that file. Maybe `👾.jl` then?

**Pull request merged**
