### PR TITLE
Add monkey macro to replace try/catch/finally, solves #9

### PR DESCRIPTION
**Pull request by FPGro**

### CODE REVIEW

**Comment by theogf** [comment]
I think just the `export` is missing!
Feel free to add :bomb: as `error`, that's a good one!

**Comment by FPGro** [comment]
Closes #9 :)

**Comment by FPGro** [comment]
@theogf Sorry for that last fail, I thought I fixed this already. Should be fine now.

**Comment by theogf** [comment]
Hmm also my autocommit for the README seems to have some trouble, I'll just fix that by hand. LGTM once the tests pass!

**Comment by FPGro** [comment]
Yeah the docs fail seems unrelated, but if does fail with Julia v1. Should I make the macro conditional on Julia >=1.1?

**Comment by theogf** [comment]
I think if you replace instances of `isnothing(x)` by `x === nothing` this should pass as well on 1.0

**Comment by FPGro** [comment]
Okay that's interesting, lets see.

**Pull request merged**
